theme: jekyll-theme-minimal
title: Finance Bros
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: PreProcessing
    url: PreProcessing
