theme: jekyll-theme-minimal
title: 'ESG ETFs: Is it possible to find financial strength whilst being socially responsible?'
description: A deep dive into how ESG funds behave in comparision to the rest of the market.
show_downloads: True
navigation:
  - title: Introduction & Dataset
    url: /
  - title: Example
    url: example
  - title: Volatility
    url: volatility
  - title: Crisis Reaction
    url: crisis
  - title: Long Term Performance
    url: long
  - title: The Team
    url: team
markdown: kramdown
kramdown:
  math_engine: mathjax

